version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    volumes:
      - .:/note_app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
