# Generated by Django 4.0 on 2022-01-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='notes',
        ),
    ]
